version: "3.8"

services:
  server:
    container_name: tp-voto-electronico
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: '8000'
      DATABASE_DRIVER: postgres
      DATABASE_URI: postgresql://root:toor@postgres/votoElectronico?sslmode=disable
    ports:
      - '8000:8000'
  db:
    container_name: voto-electronico-postgres
    image: 'postgres'
    environment:
      POSTGRES_DB: votoElectronico
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - '5432:5432'
