version: "3.8"

services:
  server:
    container_name: tp-voto-electronico
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      EXPRESS_PORT: '8001'
      DATABASE_DRIVER: postgres
      DATABASE_URI: postgresql://root:toor@postgres/votoElectronico?sslmode=disable
    ports:
      - '8001:8001'
    depends_on:
      - db
  db:
    container_name: voto-electronico-postgres
    image: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: votoElectronico
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - '5432:5432'

volumes:
  db_data: